### ISSUE TITLE
Changing Background Color and Customization of Toast.

### ISSUE THREAD

**Issue by Afaqrehman98** [Shashank02051997/FancyToast-Android#25]
Hi,
I am unable to change the background color or customize the toast. I want to increase its Width and Height. and even change the color of the Toast's background.

**Comment by Shashank02051997** [comment]
@Afaqrehman98 you can't customize the background color... there are only selected sets of toast is there with selected sets of color only... You can't change the width and height of the toast because it is completely dependent on the text length...

If you want all of these changes I will help u with them...we can chat and I will guide you on how you can do these changes

**Comment by Afaqrehman98** [comment]
Yeah sure. Kindly tell me a medium where I can contact you. Appreciate your gesture man.

**Comment by Shashank02051997** [comment]
@Afaqrehman98 is your issue get resolved

**Comment by Shashank02051997** [comment]
@Afaqrehman98 i am closing the issue. If you need any help you can connect me directly
